name: Streamlit Keep Alive

on:
  schedule:
    # Runs at the start of every 6th hour (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history to allow amending

      - name: Update timestamp
        run: echo $(date) > heartbeat.txt

      - name: Keep-Alive Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add heartbeat.txt
          # Amends the existing commit if it exists, otherwise creates one
          git commit --amend -m "Heartbeat: Keep Streamlit App Awake" || git commit -m "Heartbeat: Keep Streamlit App Awake"
          git push --force